### ISSUE TITLE
some content does not work on the API

### ISSUE THREAD

**Issue by joelanman** [alphagov/content-store#325]
If I request `/government/history/past-prime-ministers/gordon-brown` from the content api - a page which exists on gov.uk, it redirects to `/government`. I would expect the information for the original page.

**Comment by tijmenb** [comment]
Not all pages are currently in the content store. This is known (https://trello.com/c/Q17pqbM8/20-not-all-whitehall-content-is-migrated) but is unlikely to be fixed soon, unless there is a immediate need to.

**Comment by joelanman** [comment]
Is this mentioned in any documentation? I think it should at least be documented, and I think it's a valid issue that should be left open?

**Comment by cbaines** [comment]
> Is this mentioned in any documentation? I think it should at least be documented, and I think it's a valid issue that should be left open?

If it's worth tracking this, then I think closer to Whitehall is better, as this relates to Whitehall, and not the Content Store.

I think there might be some documentation describing different content published by Whitehall, and how it is rendered, but I couldn't find it.
